version: '3'

networks:
  backend:

services:
  proxysql:
    image: proxysql/proxysql
    container_name: proxy-sql
    ports:
    - "3306:3306"
    - "6032:6032"
    - "6070:6070"
    volumes:
    - ./proxysql.cnf:/etc/proxysql.cnf
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:5.7.33
    container_name: mysql-proxysql
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: datamasking
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - backend

  sqlpad:
    image: sqlpad/sqlpad
    container_name: sqlpad-proxysql
    environment:
      - SQLPAD_ADMIN=admin
      - SQLPAD_ADMIN_PASSWORD=admin
    volumes:
      - ./sqlpad:/var/lib/sqlpad
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - proxysql
    networks:
      - backend